version: '3'
services:
  siab:
    image: 'sspreitzer/shellinabox'
    environment:
      - SIAB_SSL=false
      - SIAB_PASSWORD=Test123
#      - SIAB_USERCSS=Reverse
    ports:
      - '4200:4200'